// AUTOGENERATED FILE. Edit config.cpp.tpl instead. This file will be overwritten by the build script

#define _ARMA_

class CfgPatches
{
	class KAT_Gear_DressUniforms
	{
		author = "MisfitMaid";
		addonRootClass = "KAT_Gear";
		requiredAddons[] = {"KAT_Gear"};
		requiredVersion = 0.1;
		units[] = {};
		weapons[] = {
						"KAT_Dress_Uniform_Generic",
			"KAT_Dress_Uniform_hayessarah",
			"KAT_Dress_Uniform_reidmabellee",
			"KAT_Dress_Uniform_barneschloe",
			"KAT_Dress_Uniform_clinejohnathan",
			"KAT_Dress_Uniform_cooperlaura",
			"KAT_Dress_Uniform_lanevictoria",
			"KAT_Dress_Uniform_morningstarhyena",
			"KAT_Dress_Uniform_xnselnnetaylor7hb",
			"KAT_Dress_Uniform_tessag216",
			"KAT_Dress_Uniform_kertzmichael",
			"KAT_Dress_Uniform_frostcarter",
			"KAT_Dress_Uniform_hunterkarl",
			"KAT_Dress_Uniform_khanowen",
			"KAT_Dress_Uniform_laecavassena",
			"KAT_Dress_Uniform_prenticegenevieve",
			"KAT_Dress_Uniform_raideralex",
			"KAT_Dress_Uniform_wolftalon"
		};
	};
};
class XtdGearModels
{
	class CfgWeapons
	{
		class KAT_DressUniforms
		{
			label = "[Azrael] Dress Uniforms";
			author = "MisfitMaid";
			options[] = {"type"};
			class type
			{
				label = "type";
				values[] = {"Generic", "Hayes", "Reid", "Barnes", "Cline", "Cooper", "Lane", "Morningstar", "Selänne", "Tessa G216", "Kertz", "Frost", "Hunter", "Khan", "Laeca", "Prentice", "Raider", "Wolf"};
				alwaysSelectable = 1;
			};
		};
	};
};
class XtdGearInfos
{
	class CfgWeapons
	{
				class KAT_Dress_Uniform_Generic {model = "KAT_DressUniforms"; type = "Generic";};
		class KAT_Dress_Uniform_hayessarah {model = "KAT_DressUniforms"; type = "Hayes";};
		class KAT_Dress_Uniform_reidmabellee {model = "KAT_DressUniforms"; type = "Reid";};
		class KAT_Dress_Uniform_barneschloe {model = "KAT_DressUniforms"; type = "Barnes";};
		class KAT_Dress_Uniform_clinejohnathan {model = "KAT_DressUniforms"; type = "Cline";};
		class KAT_Dress_Uniform_cooperlaura {model = "KAT_DressUniforms"; type = "Cooper";};
		class KAT_Dress_Uniform_lanevictoria {model = "KAT_DressUniforms"; type = "Lane";};
		class KAT_Dress_Uniform_morningstarhyena {model = "KAT_DressUniforms"; type = "Morningstar";};
		class KAT_Dress_Uniform_xnselnnetaylor7hb {model = "KAT_DressUniforms"; type = "Selänne";};
		class KAT_Dress_Uniform_tessag216 {model = "KAT_DressUniforms"; type = "Tessa G216";};
		class KAT_Dress_Uniform_kertzmichael {model = "KAT_DressUniforms"; type = "Kertz";};
		class KAT_Dress_Uniform_frostcarter {model = "KAT_DressUniforms"; type = "Frost";};
		class KAT_Dress_Uniform_hunterkarl {model = "KAT_DressUniforms"; type = "Hunter";};
		class KAT_Dress_Uniform_khanowen {model = "KAT_DressUniforms"; type = "Khan";};
		class KAT_Dress_Uniform_laecavassena {model = "KAT_DressUniforms"; type = "Laeca";};
		class KAT_Dress_Uniform_prenticegenevieve {model = "KAT_DressUniforms"; type = "Prentice";};
		class KAT_Dress_Uniform_raideralex {model = "KAT_DressUniforms"; type = "Raider";};
		class KAT_Dress_Uniform_wolftalon {model = "KAT_DressUniforms"; type = "Wolf";};
	};
};
class CfgWeapons
{
	class OPTRE_UNSC_Army_Uniform_WDL;
	class OPTRE_UNSC_Dress_Uniform_gray: OPTRE_UNSC_Army_Uniform_WDL
	{
		class ItemInfo;
	};

		class KAT_Dress_Uniform_Generic: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Generic)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_Generic_Soldier"; };
	};
	class KAT_Dress_Uniform_hayessarah: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Hayes)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_hayessarah_Soldier"; };
	};
	class KAT_Dress_Uniform_reidmabellee: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Reid)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_reidmabellee_Soldier"; };
	};
	class KAT_Dress_Uniform_barneschloe: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Barnes)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_barneschloe_Soldier"; };
	};
	class KAT_Dress_Uniform_clinejohnathan: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Cline)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_clinejohnathan_Soldier"; };
	};
	class KAT_Dress_Uniform_cooperlaura: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Cooper)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_cooperlaura_Soldier"; };
	};
	class KAT_Dress_Uniform_lanevictoria: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Lane)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_lanevictoria_Soldier"; };
	};
	class KAT_Dress_Uniform_morningstarhyena: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Morningstar)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_morningstarhyena_Soldier"; };
	};
	class KAT_Dress_Uniform_xnselnnetaylor7hb: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Selänne)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_xnselnnetaylor7hb_Soldier"; };
	};
	class KAT_Dress_Uniform_tessag216: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Tessa G216)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_tessag216_Soldier"; };
	};
	class KAT_Dress_Uniform_kertzmichael: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Kertz)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_kertzmichael_Soldier"; };
	};
	class KAT_Dress_Uniform_frostcarter: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Frost)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_frostcarter_Soldier"; };
	};
	class KAT_Dress_Uniform_hunterkarl: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Hunter)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_hunterkarl_Soldier"; };
	};
	class KAT_Dress_Uniform_khanowen: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Khan)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_khanowen_Soldier"; };
	};
	class KAT_Dress_Uniform_laecavassena: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Laeca)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_laecavassena_Soldier"; };
	};
	class KAT_Dress_Uniform_prenticegenevieve: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Prentice)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_prenticegenevieve_Soldier"; };
	};
	class KAT_Dress_Uniform_raideralex: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Raider)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_raideralex_Soldier"; };
	};
	class KAT_Dress_Uniform_wolftalon: OPTRE_UNSC_Dress_Uniform_gray {
		displayName = "[Azrael] Dress Uniform (Wolf)";
		class ItemInfo: ItemInfo { uniformClass = "KAT_Dress_Uniform_wolftalon_Soldier"; };
	};
};
class CfgVehicles
{
	class KAT_Base_Uniform;

		class KAT_Dress_Uniform_Generic_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_Generic";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\_uniform_generic.paa"};
	};
	class KAT_Dress_Uniform_hayessarah_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_hayessarah";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_hayessarah.paa"};
	};
	class KAT_Dress_Uniform_reidmabellee_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_reidmabellee";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_reidmabellee.paa"};
	};
	class KAT_Dress_Uniform_barneschloe_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_barneschloe";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_barneschloe.paa"};
	};
	class KAT_Dress_Uniform_clinejohnathan_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_clinejohnathan";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_clinejohnathan.paa"};
	};
	class KAT_Dress_Uniform_cooperlaura_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_cooperlaura";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_cooperlaura.paa"};
	};
	class KAT_Dress_Uniform_lanevictoria_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_lanevictoria";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_lanevictoria.paa"};
	};
	class KAT_Dress_Uniform_morningstarhyena_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_morningstarhyena";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_morningstarhyena.paa"};
	};
	class KAT_Dress_Uniform_xnselnnetaylor7hb_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_xnselnnetaylor7hb";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_xnselnnetaylor7hb.paa"};
	};
	class KAT_Dress_Uniform_tessag216_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_tessag216";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_tessag216.paa"};
	};
	class KAT_Dress_Uniform_kertzmichael_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_kertzmichael";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_kertzmichael.paa"};
	};
	class KAT_Dress_Uniform_frostcarter_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_frostcarter";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_frostcarter.paa"};
	};
	class KAT_Dress_Uniform_hunterkarl_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_hunterkarl";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_hunterkarl.paa"};
	};
	class KAT_Dress_Uniform_khanowen_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_khanowen";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_khanowen.paa"};
	};
	class KAT_Dress_Uniform_laecavassena_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_laecavassena";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_laecavassena.paa"};
	};
	class KAT_Dress_Uniform_prenticegenevieve_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_prenticegenevieve";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_prenticegenevieve.paa"};
	};
	class KAT_Dress_Uniform_raideralex_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_raideralex";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_raideralex.paa"};
	};
	class KAT_Dress_Uniform_wolftalon_Soldier: KAT_Base_Uniform
	{
		dlc = "OPTRE";
		author = "MisfitMaid";
		uniformClass = "KAT_Dress_Uniform_wolftalon";
		model = "\OPTRE_UNSC_Units\Army\officer.p3d";
		hiddenSelections[] = {"camo1","camo2","insignia","clan"};
		hiddenSelectionsTextures[] = {"OPTRE_UNSC_Units\Army\data\dress_uniform_odst_co.paa","KAT_Gear\dressuniforms\uniform_wolftalon.paa"};
	};
};
