// AUTOGENERATED FILE. Edit config.cpp.tpl instead. This file will be overwritten by the build script

class CfgPatches
{
	class KAT_TicTacs
	{
		requiredVersion=0.1;
		units[]=
		{
			"Module_OPTRE_PelicanSupplyDrop",
			"KAT_TicTac_Empty",
			"KAT_TicTac_Base", "KAT_TicTac_Valkyrie", "KAT_TicTac_Berserker", "KAT_TicTac_Valhalla"
		};
		weapons[]={};
	};
};
class CfgVehicles
{
	class OPTRE_Ammo_SupplyPod_Empty;
	class Module_F;
	class KAT_TicTac_Empty: OPTRE_Ammo_SupplyPod_Empty
	{
		scope=2;
		displayName="[Azrael] Supply Pod (Empty)";
		maximumLoad=1000000;
		hiddenselections[]=
		{
			// "camo"
		};
		hiddenselectionstextures[]=
		{
			// ""
		};
        class TransportItems {};
        class TransportMagazines {};
		class TransportWeapons {};
	};

	
	class KAT_TicTac_Base: KAT_TicTac_Empty
	{
		displayName="[Azrael] Supply Pod (Base)";
		
		class TransportItems
		{
			
			class _xx_MEU_Medigel_Light {name="MEU_Medigel_Light";count=160;};
			class _xx_ACE_adenosine {name="ACE_adenosine";count=40;};
			class _xx_OPTRE_Biofoam {name="OPTRE_Biofoam";count=8;};
			class _xx_ACE_bodyBag {name="ACE_bodyBag";count=8;};
			class _xx_ACE_epinephrine {name="ACE_epinephrine";count=32;};
			class _xx_ACE_morphine {name="ACE_morphine";count=16;};
			class _xx_ACE_salineIV {name="ACE_salineIV";count=16;};
			class _xx_ACE_salineIV_500 {name="ACE_salineIV_500";count=8;};
			class _xx_ACE_salineIV_250 {name="ACE_salineIV_250";count=16;};
			class _xx_ACE_splint {name="ACE_splint";count=32;};
			class _xx_ACE_tourniquet {name="ACE_tourniquet";count=16;};
			class _xx_ACE_elasticBandage {name="ACE_elasticBandage";count=64;};
			class _xx_ACE_CableTie {name="ACE_CableTie";count=16;};
		};
	};
	class KAT_TicTac_Valkyrie: KAT_TicTac_Base
	{
		displayName="[Azrael] Supply Pod (Valkyrie)";
		
		class TransportMagazines
		{
			
			class _xx_OPTRE_36Rnd_95x40_Mag_JHP {magazine="OPTRE_36Rnd_95x40_Mag_JHP";count=20;};
			class _xx_OPTRE_60Rnd_5x23mm_Mag_JHP {magazine="OPTRE_60Rnd_5x23mm_Mag_JHP";count=10;};
			class _xx_MEU_400Rnd_762x51_AP_HV_Box {magazine="MEU_400Rnd_762x51_AP_HV_Box";count=6;};
			class _xx_TCF_12Rnd_127x40_Mag_JHP {magazine="TCF_12Rnd_127x40_Mag_JHP";count=12;};
			class _xx_TCF_12Rnd_127x40_Mag_JHPT {magazine="TCF_12Rnd_127x40_Mag_JHPT";count=4;};
			class _xx_C7_Remote_Mag {magazine="C7_Remote_Mag";count=5;};
		};
	};
	class KAT_TicTac_Berserker: KAT_TicTac_Base
	{
		displayName="[Azrael] Supply Pod (Berserker)";
		
		class TransportMagazines
		{
			
			class _xx_MEU_60Rnd_5x23mm_Mag_AP {magazine="MEU_60Rnd_5x23mm_Mag_AP";count=10;};
			class _xx_OPTRE_32Rnd_762x51_Mag_JHP {magazine="OPTRE_32Rnd_762x51_Mag_JHP";count=10;};
			class _xx_OPTRE_15Rnd_DMR_762x51_Mag_JHP {magazine="OPTRE_15Rnd_DMR_762x51_Mag_JHP";count=10;};
			class _xx_TCF_12Rnd_127x40_Mag_JHP {magazine="TCF_12Rnd_127x40_Mag_JHP";count=8;};
			class _xx_TCF_12Rnd_127x40_Mag_NARQ {magazine="TCF_12Rnd_127x40_Mag_NARQ";count=2;};
			class _xx_OPTRE_8Rnd_127x40_AP_Mag {magazine="OPTRE_8Rnd_127x40_AP_Mag";count=8;};
		};
	};
	class KAT_TicTac_Valhalla: KAT_TicTac_Base
	{
		displayName="[Azrael] Supply Pod (Valhalla)";
		
		class TransportMagazines
		{
			
			class _xx_KAT_200Rnd_95x40_Box_JHPT8 {magazine="KAT_200Rnd_95x40_Box_JHPT8";count=6;};
			class _xx_4Rnd_454Casull {magazine="4Rnd_454Casull";count=4;};
			class _xx_TCF_12Rnd_127x40_Mag_JHP {magazine="TCF_12Rnd_127x40_Mag_JHP";count=4;};
		};
	};

	class Module_OPTRE_PelicanSupplyDrop: Module_F
	{
		class Arguments
		{
			class box1
			{
				defaultValue="KAT_TicTac_Empty";
				class values
				{
					class kat_pod_none
					{
						name="-Empty-";
						value="none";
					};
					class kat_pod_empty
					{
						name="[Azrael] Supply Pod (Empty)";
						value="KAT_TicTac_Empty";
					};
					

					class kat_pod_Base
					{
						name="[Azrael] Supply Pod (Base)";
						value="KAT_TicTac_Base";
					};

					class kat_pod_Valkyrie
					{
						name="[Azrael] Supply Pod (Valkyrie)";
						value="KAT_TicTac_Valkyrie";
					};

					class kat_pod_Berserker
					{
						name="[Azrael] Supply Pod (Berserker)";
						value="KAT_TicTac_Berserker";
					};

					class kat_pod_Valhalla
					{
						name="[Azrael] Supply Pod (Valhalla)";
						value="KAT_TicTac_Valhalla";
					};
				};
			};
		};
	};
};
