// AUTOGENERATED FILE. Edit config.cpp.tpl instead. This file will be overwritten by the build script

class CfgPatches
{
	class KAT_TicTacs
	{
		requiredVersion=0.1;
		units[]=
		{
			"Module_OPTRE_PelicanSupplyDrop",
			"KAT_TicTac_Empty",
			"KAT_TicTac_Base", "KAT_TicTac_Testing"
		};
		weapons[]={};
	};
};
class CfgVehicles
{
	class OPTRE_Ammo_SupplyPod_Empty;
	class Module_F;
	class KAT_TicTac_Empty: OPTRE_Ammo_SupplyPod_Empty
	{
		scope=2;
		displayName="[Azrael] Supply Pod (Empty)";
		maximumLoad=1000000;
		hiddenselections[]=
		{
			// "camo"
		};
		hiddenselectionstextures[]=
		{
			// ""
		};
        class TransportItems {};
        class TransportMagazines {};
		class TransportWeapons {};
	};

	
	class KAT_TicTac_Base: KAT_TicTac_Empty
	{
		displayName="[Azrael] Supply Pod (Base)";
		
		class TransportItems
		{
			
			class _MEU_Medigel_Light {name="MEU_Medigel_Light";count=160;};
			class _ACE_adenosine {name="ACE_adenosine";count=40;};
			class _OPTRE_Biofoam {name="OPTRE_Biofoam";count=8;};
			class _ACE_bodyBag {name="ACE_bodyBag";count=8;};
			class _ACE_epinephrine {name="ACE_epinephrine";count=32;};
			class _ACE_morphine {name="ACE_morphine";count=16;};
			class _ACE_salineIV {name="ACE_salineIV";count=16;};
			class _ACE_salineIV_500 {name="ACE_salineIV_500";count=8;};
			class _ACE_salineIV_250 {name="ACE_salineIV_250";count=16;};
			class _ACE_splint {name="ACE_splint";count=32;};
			class _ACE_tourniquet {name="ACE_tourniquet";count=16;};
			class _ACE_elasticBandage {name="ACE_elasticBandage";count=64;};
			class _ACE_CableTie {name="ACE_CableTie";count=16;};
		};
	};
	class KAT_TicTac_Testing: KAT_TicTac_Base
	{
		displayName="[Azrael] Supply Pod (Testing)";
		
		class TransportMagazines
		{
			
			class _KAT_200Rnd_95x40_Box_JHPT8 {name="KAT_200Rnd_95x40_Box_JHPT8";count=8;};
		};
	};

	class Module_OPTRE_PelicanSupplyDrop: Module_F
	{
		class Arguments
		{
			class box1
			{
				defaultValue="KAT_TicTac_Empty";
				class values
				{
					class kat_pod_none
					{
						name="-Empty-";
						value="none";
					};
					class kat_pod_empty
					{
						name="[Azrael] Supply Pod (Empty)";
						value="KAT_TicTac_Empty";
					};
					

					class kat_pod_Base
					{
						name="[Azrael] Supply Pod (Base)";
						value="KAT_TicTac_Base";
					};

					class kat_pod_Testing
					{
						name="[Azrael] Supply Pod (Testing)";
						value="KAT_TicTac_Testing";
					};
				};
			};
		};
	};
};
