<?php
$csv = array_map('str_getcsv', explode(PHP_EOL, file_get_contents(dirname(__FILE__) . "/Supplies Reference.csv")));

array_shift($csv);
array_pop($csv);

$tictacs = [];

// 0 tictac
// 1 item
// 2 type
// 3 (ignored)
// 4 qty total
foreach ($csv as $v) {
	if (!array_key_exists($v[0], $tictacs)) {
		$tictacs[$v[0]] = ["TransportItems" => [], "TransportMagazines" => [], "TransportWeapons" => []];
	}
	$tictacs[$v[0]][$v[2]][trim($v[1])] = (int) $v[4];
}

$tpl = "
	class KAT_TicTac_%s: KAT_TicTac_%s
	{
		displayName=\"[Azrael] Supply Pod (%s)\";
		%s
	};";
$tpl_Trans = "
		class %s
		{
			%s
		};";
$tpl_Item = "
			class _%s {name=\"%s\";count=%s;};";

$tpl_Module = "

					class kat_pod_%s
					{
						name=\"[Azrael] Supply Pod (%s)\";
						value=\"KAT_TicTac_%s\";
					};";
$tpl_Define = "\"KAT_TicTac_%s\"";

$units = [];
$modules = "";
$defines = "";
foreach ($tictacs as $k => $v) {
	$units[] = sprintf($tpl_Define, $k);
	$modules .= sprintf($tpl_Module, $k, $k, $k);

	$parent = ($k == "Base") ? "Empty" : "Base";

	$transes = "";
	foreach ($v as $tk => $tv) {
		if (count($tv) == 0) continue;

		$items = "";
		foreach ($tv as $item => $qty) {
			$items .= sprintf($tpl_Item, $item, $item, $qty);
		}
		$transes .= sprintf($tpl_Trans, $tk, $items);
	}
	$defines .= sprintf($tpl, $k, $parent, $k, $transes);
}

$base = file_get_contents(dirname(__FILE__) . "/config.cpp.tpl");
$filled = sprintf($base,
	"AUTOGENERATED FILE. Edit config.cpp.tpl instead. This file will be overwritten by the build script",
	implode(", ", $units),
	$defines,
	$modules
);
file_put_contents(dirname(__FILE__) . "/config.cpp", $filled);
